services:
  - type: web
    name: risk-it
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    numInstances: 1
    autoDeployTrigger: off
